# Project 1: Hotels Data Wrangling

## Load libraries - these libraries are needed to complete the codes needed for data wrangling

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Load Data - Imperitive to load all data for inspection, cleaning and analysis
##### later on ran into problem with 9999 being an answer for adults/children/ babies so I put zero for childre/babies and I put 1 for adults. A total of 9 records. 3 for each category.

In [2]:
hotels1 = pd.read_csv ('/Users/chercher/Desktop/hotels data/hotels1.csv')

In [3]:
hotels2 = pd.read_csv ('/Users/chercher/Desktop/hotels data/hotels2.csv')

In [4]:
hotels3 = pd.read_csv ('/Users/chercher/Desktop/hotels data/hotels3.csv')

In [5]:
hotels4 = pd.read_csv ('/Users/chercher/Desktop/hotels data/hotels4A.csv')

#### later on I set it to max columns and rows using pd.set_option('display.max_columns', None) and pd.set_option('display.max_rows', None) which is causing Python to freeze during kernel. changing it back.

In [6]:
pd.set_option('display.min_rows', 10)

In [7]:
pd.set_option('display.max_columns', None)

### Calling the function for each data set - displays the first and last five rows of the data with the column headings truncated. At the bottom left the number of rows and columns are listed; check against the original data to verify everything was loaded.

In [8]:
hotels1

,reservation_id,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights
0,0,Resort Hotel,0,342,2015,July,27,1,0,0
1,1,Resort Hotel,0,737,2015,July,27,1,0,0
2,2,Resort Hotel,0,7,2015,July,27,1,0,1
3,3,Resort Hotel,0,13,2015,July,27,1,0,1
4,4,Resort Hotel,0,14,2015,July,27,1,0,2
...,...,...,...,...,...,...,...,...,...,...
495,495,Resort Hotel,0,92,2015,July,29,17,1,2
496,496,Resort Hotel,0,91,2015,July,29,17,1,2
497,497,Resort Hotel,0,38,2015,July,29,17,1,2
498,498,Resort Hotel,0,6,2015,July,29,17,1,2
499,499,Resort Hotel,0,38,2015,July,29,17,1,2

In [9]:
hotels2

,reservation_id,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,Agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,Reservation_Status,reservation_status_date
0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,2,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,3,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,2,0.0,0,BB,MOZ,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,240.0,0,Transient,103.50,1,3,Check-Out,2015-07-20
496,496,2,1.0,0,BB,BWA,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,240.0,0,Transient,118.50,0,3,Check-Out,2015-07-20
497,497,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,0,Transient,192.00,0,1,Check-Out,2015-07-20
498,498,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,142.0,0,Contract,128.27,0,0,Check-Out,2015-07-20
499,499,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,0,Transient,135.00,0,0,Check-Out,2015-07-20

In [10]:
hotels3

,reservation_id,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,company
0,500,Resort Hotel,0,13,2015,July,29,17,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,126.3,0,2,Check-Out,2015-07-20,NaN
1,501,Resort Hotel,1,32,2015,July,29,17,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,0,Transient,154.0,0,0,Canceled,2015-06-24,NaN
2,502,Resort Hotel,0,315,2015,July,29,17,1,2,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,171.0,0,Transient,96.3,0,0,Check-Out,2015-07-20,NaN
3,503,Resort Hotel,0,8,2015,July,29,17,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,0,Transient,126.3,0,2,Check-Out,2015-07-20,NaN
4,504,Resort Hotel,1,0,2015,July,29,17,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,L,C,0,No Deposit,NaN,0,Transient,136.0,0,0,Canceled,2015-07-17,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6495,6995,Resort Hotel,1,83,2016,July,29,16,1,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,0,Transient,212.0,0,0,Canceled,2016-04-24,NaN
6496,6996,Resort Hotel,1,58,2016,July,29,16,2,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,160.0,0,0,Canceled,2016-06-17,NaN
6497,6997,Resort Hotel,1,103,2016,July,29,16,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,0,Transient,180.0,0,0,Canceled,2016-06-25,NaN
6498,6998,Resort Hotel,1,35,2016,July,29,16,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,179.0,0,0,Canceled,2016-06-12,NaN
6499,6999,Resort Hotel,1,20,2016,July,29,16,2,3,1,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,0,Transient,209.0,0,0,Canceled,2016-06-27,NaN

In [11]:
hotels4

,reservation_id,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,company
0,6900,Resort Hotel,0,292,2016,July,29,10,1,0,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,72.90,0,2,Check-Out,2016-07-11,NaN
1,6901,Resort Hotel,1,149,2016,July,29,10,1,0,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,0,Transient,260.00,0,0,Canceled,2016-02-22,NaN
2,6902,Resort Hotel,1,146,2016,July,29,10,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,0,Transient,119.00,0,1,Canceled,2016-06-30,NaN
3,6903,Resort Hotel,0,292,2016,July,29,10,1,0,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,72.90,0,2,Check-Out,2016-07-11,NaN
4,6904,Resort Hotel,0,292,2016,July,29,10,1,0,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,72.90,1,2,Check-Out,2016-07-11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,0,Transient,96.14,0,0,Check-Out,2017-09-06,NaN
112486,119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,0,Transient,225.43,0,2,Check-Out,2017-09-07,NaN
112487,119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,0,Transient,157.71,0,4,Check-Out,2017-09-07,NaN
112488,119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,0,Transient,104.40,0,0,Check-Out,2017-09-07,NaN
112489,119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,0,Transient,151.20,0,2,Check-Out,2017-09-07,NaN

### Change column names so all datasets have the same column names for corresponding columns then display to make sure the columns were renamed.
#### Hotels2 requires Agent to be renamed agent and Reservation_ Status to be renamed reservation_status to match other data sets. At first the capitalization would not happen when i typed the column name. Copy and pasting from the list above worked better. Just a tip/trick.
#### Always rename the data set so that you can return to the original in the event of a mistake made down the road

In [12]:
hotels2a=hotels2.rename(columns={'Agent': 'agent', 'Reservation_Status': 'reservation_status'})
hotels2a

,reservation_id,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,2,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,3,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,2,0.0,0,BB,MOZ,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,240.0,0,Transient,103.50,1,3,Check-Out,2015-07-20
496,496,2,1.0,0,BB,BWA,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,240.0,0,Transient,118.50,0,3,Check-Out,2015-07-20
497,497,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,0,Transient,192.00,0,1,Check-Out,2015-07-20
498,498,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,142.0,0,Contract,128.27,0,0,Check-Out,2015-07-20
499,499,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,0,Transient,135.00,0,0,Check-Out,2015-07-20

### Merge data sets two by two until the data is in one file
#### Display the new data sets to make sure number of rows and columns are in tact.

In [13]:
hotels = pd.concat([hotels1, hotels2a])
hotels

,reservation_id,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,0,Resort Hotel,0.0,342.0,2015.0,July,27.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Resort Hotel,0.0,737.0,2015.0,July,27.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Resort Hotel,0.0,7.0,2015.0,July,27.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Resort Hotel,0.0,13.0,2015.0,July,27.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Resort Hotel,0.0,14.0,2015.0,July,27.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,BB,MOZ,Online TA,TA/TO,0.0,0.0,0.0,A,A,3.0,No Deposit,240.0,0.0,Transient,103.50,1.0,3.0,Check-Out,2015-07-20
496,496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,0.0,BB,BWA,Online TA,TA/TO,0.0,0.0,0.0,A,A,3.0,No Deposit,240.0,0.0,Transient,118.50,0.0,3.0,Check-Out,2015-07-20
497,497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,0.0,HB,PRT,Online TA,TA/TO,0.0,0.0,0.0,E,E,1.0,No Deposit,240.0,0.0,Transient,192.00,0.0,1.0,Check-Out,2015-07-20
498,498,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,BB,GBR,Offline TA/TO,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,142.0,0.0,Contract,128.27,0.0,0.0,Check-Out,2015-07-20
499,499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,BB,ESP,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,240.0,0.0,Transient,135.00,0.0,0.0,Check-Out,2015-07-20

In [14]:
hotels1 = pd.concat([hotels, hotels3])
hotels1

,reservation_id,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,company
0,0,Resort Hotel,0.0,342.0,2015.0,July,27.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Resort Hotel,0.0,737.0,2015.0,July,27.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Resort Hotel,0.0,7.0,2015.0,July,27.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Resort Hotel,0.0,13.0,2015.0,July,27.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Resort Hotel,0.0,14.0,2015.0,July,27.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6495,6995,Resort Hotel,1.0,83.0,2016.0,July,29.0,16.0,1.0,1.0,2.0,0.0,0.0,HB,PRT,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,240.0,0.0,Transient,212.0,0.0,0.0,Canceled,2016-04-24,NaN
6496,6996,Resort Hotel,1.0,58.0,2016.0,July,29.0,16.0,2.0,2.0,1.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,240.0,0.0,Transient,160.0,0.0,0.0,Canceled,2016-06-17,NaN
6497,6997,Resort Hotel,1.0,103.0,2016.0,July,29.0,16.0,2.0,2.0,2.0,0.0,0.0,BB,ESP,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,240.0,0.0,Transient,180.0,0.0,0.0,Canceled,2016-06-25,NaN
6498,6998,Resort Hotel,1.0,35.0,2016.0,July,29.0,16.0,2.0,2.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,240.0,0.0,Transient,179.0,0.0,0.0,Canceled,2016-06-12,NaN
6499,6999,Resort Hotel,1.0,20.0,2016.0,July,29.0,16.0,2.0,3.0,1.0,0.0,0.0,BB,LUX,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,240.0,0.0,Transient,209.0,0.0,0.0,Canceled,2016-06-27,NaN

In [15]:
Hotels = pd.concat([hotels1, hotels4])
Hotels

,reservation_id,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,company
0,0,Resort Hotel,0.0,342.0,2015.0,July,27.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Resort Hotel,0.0,737.0,2015.0,July,27.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Resort Hotel,0.0,7.0,2015.0,July,27.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Resort Hotel,0.0,13.0,2015.0,July,27.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Resort Hotel,0.0,14.0,2015.0,July,27.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,119385,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,0.0,0.0,BB,BEL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,394.0,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06,NaN
112486,119386,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,9.0,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07,NaN
112487,119387,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,9.0,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07,NaN
112488,119388,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,89.0,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07,NaN
112489,119389,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,0.0,0.0,HB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,9.0,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07,NaN

### Drop duplicate rows - 10 duplicate rows were dropped

In [16]:
Hotels.drop_duplicates(subset=None, keep='first', inplace=False, ignore_index=False)

,reservation_id,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,company
0,0,Resort Hotel,0.0,342.0,2015.0,July,27.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Resort Hotel,0.0,737.0,2015.0,July,27.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Resort Hotel,0.0,7.0,2015.0,July,27.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Resort Hotel,0.0,13.0,2015.0,July,27.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Resort Hotel,0.0,14.0,2015.0,July,27.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,119385,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,0.0,0.0,BB,BEL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,394.0,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06,NaN
112486,119386,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,9.0,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07,NaN
112487,119387,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,9.0,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07,NaN
112488,119388,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,89.0,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07,NaN
112489,119389,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,0.0,0.0,HB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,9.0,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07,NaN

## Assess for erroneous/inconsistent data

#### Project instructions indicated to look at the 'hotel' column and the 'arrival_date_month' column for starters. The only way to learn what the respondents answered is to do a value counts on each question.
#### start by displaying the questions which are the columns.

In [17]:
for col in Hotels.columns:
    print(col)

reservation_id
hotel
is_canceled
lead_time
arrival_date_year
arrival_date_month
arrival_date_week_number
arrival_date_day_of_month
stays_in_weekend_nights
stays_in_week_nights
adults
children
babies
meal
country
market_segment
distribution_channel
is_repeated_guest
previous_cancellations
previous_bookings_not_canceled
reserved_room_type
assigned_room_type
booking_changes
deposit_type
agent
days_in_waiting_list
customer_type
adr
required_car_parking_spaces
total_of_special_requests
reservation_status
reservation_status_date
company

#### reservation_id looked weird because the data mirriors the row number of the csv file rather than actual ID numbers. The value_counts also suggests deleting the column is best. There is nothing to analyze by here.

#### This made me curious if the other answers all came from the timeframe, day, etc. further investigating with value.counts

In [18]:
Hotels.reservation_id.value_counts()

0        2
407      2
151      2
105      2
23       2
        ..
69131    1
67082    1
73225    1
71176    1
2047     1
Name: reservation_id, Length: 119390, dtype: int64

#### The answer key on Kaggle shows 'hotel' could be Resort Hotel or City Hotel. Both are shown with different capitalization which creates several entries instead of just two. This can be recoded to an integer but all spellings must be included to make one category for City Hotel and one for Resort Hotel.

In [19]:
Hotels.hotel.value_counts()

City Hotel      79310
Resort Hotel    40140
RESORT hotel       12
city HOTEL         12
Resort HOTEL        8
CITY hotel          8
Name: hotel, dtype: int64

##### Luckily the creator of the data already coded the answers for this question: 0 not canceled, 1=canceled

In [20]:
Hotels.is_canceled.value_counts

<bound method IndexOpsMixin.value_counts of 0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ...
112485    0.0
112486    0.0
112487    0.0
112488    0.0
112489    0.0
Name: is_canceled, Length: 119990, dtype: float64>

### lead_time is the number of days between booking and arrival. It preliminarily looks like a lot of people book and arrive on the same day. It also looks like more people book and arrive within 1-7 days.

In [21]:
Hotels.lead_time.value_counts()

0.0      6347
1.0      3460
2.0      2069
3.0      1816
4.0      1715
         ...
737.0       1
532.0       1
463.0       1
458.0       1
370.0       1
Name: lead_time, Length: 479, dtype: int64

#### Ok, people stayed in 2015, 2016 and 2017. Undersampled for 2015. It was a leap year in 2016.

In [22]:
Hotels.arrival_date_year.value_counts()

2016.0    56807
2017.0    40687
2015.0    21996
Name: arrival_date_year, dtype: int64

#### 'arrival_date_month' has the some months all caps and some initial caps. Recode to only 12 months with initital caps.

In [23]:
Hotels.arrival_date_month.value_counts()

August       13872
July         12756
May          11786
October      11155
April        11084
June         10934
September    10503
March         9789
February      8063
November      6789
December      6775
January       5924
MARCH            5
JULY             5
NOVEMBER         5
AUGUST           5
FEBRUARY         5
APRIL            5
DECEMBER         5
MAY              5
OCTOBER          5
SEPTEMBER        5
JANUARY          5
JUNE             5
Name: arrival_date_month, dtype: int64

#### There are 52 weeks in a year. This will be better analyzed by season. But the most popular weeks are 30, 32, 33 and 34 are in July and August; a prime time for vacations.
#### This data shows 53 weeks as an option because 2016 was a leap year.

In [24]:
Hotels.arrival_date_week_number.value_counts()

33.0    3580
30.0    3087
32.0    3045
34.0    3040
18.0    2926
29.0    2863
21.0    2854
28.0    2853
17.0    2805
20.0    2785
42.0    2756
31.0    2741
41.0    2699
15.0    2689
27.0    2664
25.0    2663
38.0    2661
23.0    2621
35.0    2593
39.0    2581
22.0    2546
24.0    2498
13.0    2416
16.0    2405
19.0    2402
40.0    2397
26.0    2391
43.0    2352
44.0    2272
14.0    2264
37.0    2229
8.0     2216
36.0    2167
10.0    2149
9.0     2117
7.0     2109
12.0    2083
11.0    2070
45.0    1941
53.0    1816
49.0    1782
47.0    1685
46.0    1574
6.0     1508
50.0    1505
48.0    1504
4.0     1487
5.0     1387
3.0     1319
2.0     1218
52.0    1195
1.0     1047
51.0     933
Name: arrival_date_week_number, dtype: int64

#### Keeping arrival_date_day_of_month due to variety of answers to analyze by. Look at it by week to see trends. Hypothesis: mid-month is when most people arrive.

In [25]:
Hotels.arrival_date_day_of_month.value_counts()

17.0    4406
5.0     4317
15.0    4218
25.0    4160
26.0    4147
12.0    4108
9.0     4096
16.0    4084
2.0     4055
19.0    4052
20.0    4032
18.0    4002
24.0    3993
28.0    3946
8.0     3921
3.0     3855
30.0    3853
14.0    3834
6.0     3833
27.0    3802
21.0    3767
4.0     3763
13.0    3756
7.0     3665
1.0     3626
11.0    3616
23.0    3616
22.0    3596
10.0    3583
29.0    3580
31.0    2208
Name: arrival_date_day_of_month, dtype: int64

### There are 52 saturdays and 52 sundays in a year. By far, people are only staying 0, 1 or 2 weekend nights per year.

In [26]:
Hotels.stays_in_weekend_nights.value_counts()

0.0     52024
2.0     33350
1.0     30650
4.0      1859
3.0      1263
6.0       153
5.0        79
8.0        60
7.0        19
9.0        11
10.0        7
12.0        5
16.0        3
13.0        3
14.0        2
18.0        1
19.0        1
Name: stays_in_weekend_nights, dtype: int64

#### There are 261 week days in a year. The majority of people stay 0-5 week nights a year with the highest being 1, 2, 3 or 5 days.

In [27]:
Hotels.stays_in_week_nights.value_counts()

2.0     33705
1.0     30314
3.0     22276
5.0     11103
4.0      9577
0.0      7650
6.0      1500
10.0     1039
7.0      1034
8.0       658
9.0       232
15.0       85
11.0       56
19.0       44
12.0       42
20.0       41
14.0       35
13.0       27
16.0       16
21.0       15
22.0        7
18.0        6
25.0        6
30.0        5
17.0        4
24.0        3
40.0        2
26.0        1
34.0        1
41.0        1
35.0        1
33.0        1
50.0        1
42.0        1
32.0        1
Name: stays_in_week_nights, dtype: int64

### Null values must be removed. Coerce to integer.
### Hypothesis - One or two adults booked to stay per visit.

In [28]:
Hotels.adults.value_counts

<bound method IndexOpsMixin.value_counts of 0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
112485    2.0
112486    3.0
112487    2.0
112488    2.0
112489    2.0
Name: adults, Length: 119990, dtype: float64>

#### Some groups checked in due to the number of adults being higher than 1 or 2.

In [29]:
Hotels.adults.unique()

array([nan,  2.,  1.,  3.,  4., 40., 26., 50., 27., 55.,  0., 20.,  6.,
        5., 10.])

#### Most often the number of children that were booked to stay was 0, 1 or 2.

In [30]:
Hotels.children.value_counts()

0.0     110881
1.0       4866
2.0       3662
3.0         76
10.0         1
Name: children, dtype: int64

### Most people did not go to the hotel with a baby in tow. Those who did usually only had one baby.

In [31]:
Hotels.babies.value_counts()

0.0     118570
1.0        903
2.0         15
9.0          1
10.0         1
Name: babies, dtype: int64

#### According to the answer key options for meal were BB bed and breakfast, HB hotel breakfast, or other. I do not know what SC or FB stand for. Can group all those as other without explanantion of what lies within.
#### Almost everyone ate at a Bed and Breakfast (BB) followed by Hotel Breakfast (HB). I do not know what SC and FB stand for.

In [32]:
Hotels.meal.value_counts()

BB           92397
HB           14475
SC           10650
Undefined     1170
FB             798
Name: meal, dtype: int64

#### The data shows most coming from PRT. Need to show the top two and group all else together. Using .unique() to see just how many countries participated.

In [33]:
Hotels.country.value_counts()

PRT    48649
GBR    12133
FRA    10417
ESP     8583
DEU     7288
       ...
PLW        1
MRT        1
KIR        1
AIA        1
CYM        1
Name: country, Length: 177, dtype: int64

In [34]:
Hotels.country.unique()

array([nan, 'PRT', 'GBR', 'USA', 'ESP', 'IRL', 'FRA', 'ROU', 'NOR', 'OMN',
       'ARG', 'POL', 'DEU', 'BEL', 'CHE', 'CN', 'GRC', 'ITA', 'NLD',
       'DNK', 'RUS', 'SWE', 'AUS', 'EST', 'CZE', 'BRA', 'FIN', 'MOZ',
       'BWA', 'LUX', 'SVN', 'ALB', 'IND', 'CHN', 'MEX', 'MAR', 'UKR',
       'SMR', 'LVA', 'PRI', 'SRB', 'CHL', 'AUT', 'BLR', 'LTU', 'TUR',
       'ZAF', 'AGO', 'ISR', 'CYM', 'ZMB', 'CPV', 'ZWE', 'DZA', 'KOR',
       'CRI', 'HUN', 'ARE', 'TUN', 'JAM', 'HRV', 'HKG', 'IRN', 'GEO',
       'AND', 'GIB', 'URY', 'JEY', 'CAF', 'CYP', 'COL', 'GGY', 'KWT',
       'NGA', 'MDV', 'VEN', 'SVK', 'FJI', 'KAZ', 'PAK', 'IDN', 'LBN',
       'PHL', 'SEN', 'SYC', 'AZE', 'BHR', 'NZL', 'THA', 'DOM', 'MKD',
       'MYS', 'ARM', 'JPN', 'LKA', 'CUB', 'CMR', 'BIH', 'MUS', 'COM',
       'SUR', 'UGA', 'BGR', 'CIV', 'JOR', 'SYR', 'SGP', 'BDI', 'SAU',
       'VNM', 'PLW', 'QAT', 'EGY', 'PER', 'MLT', 'MWI', 'ECU', 'MDG',
       'ISL', 'UZB', 'NPL', 'BHS', 'MAC', 'TGO', 'TWN', 'DJI', 'STP',
       'KNA', 'ETH', 'IRQ', 'HND', 'RWA', 'KHM', 'MCO', 'BGD', 'IMN',
       'TJK', 'NIC', 'BEN', 'VGB', 'TZA', 'GAB', 'GHA', 'TMP', 'GLP',
       'KEN', 'LIE', 'GNB', 'MNE', 'UMI', 'MYT', 'FRO', 'MMR', 'PAN',
       'BFA', 'LBY', 'MLI', 'NAM', 'BOL', 'PRY', 'BRB', 'ABW', 'AIA',
       'SLV', 'DMA', 'PYF', 'GUY', 'LCA', 'ATA', 'GTM', 'ASM', 'MRT',
       'NCL', 'KIR', 'SDN', 'ATF', 'SLE', 'LAO'], dtype=object)

#### market_segment deals with how consumers booked their accomodations. Online TA -Travel Agent is by far the most popular choice.

In [35]:
Hotels.market_segment.value_counts()

Online TA        56562
Offline TA/TO    24224
Groups           19811
Direct           12616
Corporate         5295
Complementary      743
Aviation           237
Undefined            2
Name: market_segment, dtype: int64

#### distribution_channel for most is TA/TO Travel Agent or Travel Office.

In [36]:
Hotels.distribution_channel.value_counts()

TA/TO        97960
Direct       14655
Corporate     6677
GDS            193
Undefined        5
Name: distribution_channel, dtype: int64

#### is_repeated_guest, previous_cancellations, previous_bookings_not_canceled 
#### answers were 0 not repeated guest or not previous cancellation, 1=repeated guest or previous cancellation. Almost all were not repeat guests 0.

In [37]:
Hotels.is_repeated_guest.value_counts()

0.0    115680
1.0      3810
Name: is_repeated_guest, dtype: int64

### Most didn't cancel previously. A small percentage canceled once.

In [38]:
Hotels.previous_cancellations.value_counts()

0.0     113006
1.0       6051
2.0        116
3.0         65
24.0        48
11.0        35
4.0         31
26.0        26
25.0        25
6.0         22
5.0         19
19.0        19
14.0        14
13.0        12
21.0         1
Name: previous_cancellations, dtype: int64

### This is the number of previous bookings NOT canceled before the current booking. Almost all did not cancel a previous booking before they made the current one. 
### .unique() to display all the possible answers.

In [39]:
Hotels.previous_bookings_not_canceled.value_counts()

0.0     115870
1.0       1542
2.0        580
3.0        333
4.0        229
         ...
63.0         1
59.0         1
34.0         1
53.0         1
66.0         1
Name: previous_bookings_not_canceled, Length: 73, dtype: int64

In [40]:
Hotels.previous_bookings_not_canceled.unique()

array([nan,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,
       12., 13., 14., 15., 16., 17., 18., 20., 21., 22., 23., 24., 25.,
       27., 28., 29., 30., 19., 26., 31., 32., 33., 34., 35., 36., 37.,
       38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.,
       51., 52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63.,
       64., 65., 66., 67., 68., 69., 70., 71., 72.])

#### Code of reserved_room_type (key unavailable). A and D types are most prevelant with A showing up more than double.

In [41]:
Hotels.reserved_room_type.value_counts()

A    86046
D    19220
E     6548
F     2900
G     2102
B     1118
C      934
H      604
P       12
L        6
Name: reserved_room_type, dtype: int64

#### assigned_room_type also shows A and D most.

In [42]:
Hotels.assigned_room_type.value_counts()

A    74104
D    25341
E     7820
F     3754
G     2561
C     2377
B     2163
H      715
I      363
K      279
P       12
L        1
Name: assigned_room_type, dtype: int64

#### Number of changes made to booking since it was placed is usually 0. rarely are there changes. If there are it's 1 or 2 changes.

In [43]:
Hotels.booking_changes.value_counts()

0.0     101402
1.0      12708
2.0       3809
3.0        927
4.0        377
5.0        118
6.0         63
7.0         31
8.0         17
9.0          8
10.0         6
13.0         5
14.0         5
15.0         3
17.0         2
12.0         2
16.0         2
11.0         2
18.0         1
21.0         1
20.0         1
Name: booking_changes, dtype: int64

### Most often no deposit was required for the bookings.

In [44]:
Hotels.deposit_type.value_counts()

No Deposit    104741
Non Refund     14587
Refundable       162
Name: deposit_type, dtype: int64

#### the ID of the travel agency that made the booking is listed here. Agent 9 made the majority of bookings by more than twice the number of bookings agency 240 made. This is in line with most booking through a TA/TO.
#### .unique() to see how many agent numbers there are.

In [45]:
Hotels.agent.value_counts()

9.0      31962
240.0    14005
1.0       7191
14.0      3640
7.0       3539
         ...
304.0        1
431.0        1
278.0        1
450.0        1
114.0        1
Name: agent, Length: 333, dtype: int64

In [46]:
Hotels.agent.unique()

array([ nan, 304., 240., 303.,  15., 241.,   8., 250., 115.,   5., 175.,
       134., 156., 243., 242.,   3., 105.,  40., 147., 306., 184.,  96.,
         2., 127.,  95., 146.,   9., 177.,   6., 143., 244., 149., 167.,
       300., 171., 305.,  67., 196., 152., 142., 261., 104.,  36.,  26.,
        29., 258., 110.,  71., 181.,  88., 251., 275.,  69., 248., 208.,
       256., 314., 126., 281., 273., 253., 185., 330., 334., 328., 326.,
       321., 324., 313.,  38., 155.,  68., 335., 308., 332.,  94., 348.,
       310., 339., 375.,  66., 327., 387., 298.,  91., 245., 385., 257.,
       393., 168., 405., 249., 315.,  75., 128., 307.,  11., 436.,   1.,
       201., 183., 223., 368., 336., 291., 464., 411., 481.,  10., 154.,
       468., 410., 390., 440., 495., 492., 493., 434.,  57., 531., 420.,
       483., 526., 472., 429.,  16., 446.,  34.,  78., 139., 252., 270.,
        47., 114., 301., 193., 182., 135., 350., 195., 352., 355., 159.,
       363., 384., 360., 331., 367.,  64., 406., 163., 414., 333., 427.,
       431., 430., 426., 438., 433., 418., 441., 282., 432.,  72., 450.,
       180., 454., 455.,  59., 451., 254., 358., 469., 165., 467., 510.,
       337., 476., 502., 527., 479., 508., 535., 302., 497., 187.,  13.,
         7.,  27.,  14.,  22.,  17.,  28.,  42.,  20.,  19.,  45.,  37.,
        61.,  39.,  21.,  24.,  41.,  50.,  30.,  54.,  52.,  12.,  44.,
        31.,  83.,  32.,  63.,  60.,  55.,  56.,  89.,  87., 118.,  86.,
        85., 210., 214., 129., 179., 138., 174., 170., 153.,  93., 151.,
       119.,  35., 173.,  58.,  53., 133.,  79., 235., 192., 191., 236.,
       162., 215., 157., 287., 132., 234.,  98.,  77., 103., 107., 262.,
       220., 121., 205., 378.,  23., 296., 290., 229.,  33., 286., 276.,
       425., 484., 323., 403., 219., 394., 509., 111., 423.,   4.,  70.,
        82.,  81.,  74.,  92.,  99.,  90., 112., 117., 106., 148., 158.,
       144., 211., 213., 216., 232., 150., 267., 227., 247., 278., 280.,
       285., 289., 269., 295., 265., 288., 122., 294., 325., 341., 344.,
       346., 359., 283., 364., 370., 371.,  25., 141., 391., 397., 416.,
       404., 299., 197.,  73., 354., 444., 408., 461., 388., 453., 459.,
       474., 475., 480., 449.])

#### Null Values to remove. Only about 3K people were on the wait list. .unique() to see how many days.

In [47]:
Hotels.days_in_waiting_list.value_counts()

0.0      115792
39.0        227
58.0        164
44.0        141
31.0        127
          ...
37.0          1
183.0         1
81.0          1
73.0          1
109.0         1
Name: days_in_waiting_list, Length: 128, dtype: int64

In [48]:
Hotels.days_in_waiting_list.unique()

array([ nan,   0.,  50.,  47.,  65., 122.,  75., 101., 150., 125.,  14.,
        60.,  34., 100.,  22., 121.,  61.,  39.,   5.,   1.,   8., 107.,
        43.,  52.,   2.,  11., 142., 116.,  13.,  44.,  97.,  83.,   4.,
       113.,  18.,  20., 185.,  93., 109.,   6.,  37., 105., 154.,  64.,
        99.,  38.,  48.,  33.,  77.,  21.,  80.,  59.,  40.,  58.,  89.,
        53.,  49.,  69.,  87.,  91.,  57., 111.,  79.,  98.,  85.,  63.,
        15.,   3.,  41., 224.,  31.,  56., 187., 176.,  71.,  55.,  96.,
       236., 259., 207., 215., 160., 120.,  30.,  32.,  27.,  62.,  24.,
       108., 147., 379.,  70.,  35., 178., 330., 223., 174., 162., 391.,
        68., 193.,  10.,  76.,  16.,  28.,   9., 165.,  17.,  25.,  46.,
         7.,  84., 175., 183.,  23., 117.,  12.,  54.,  26.,  73.,  45.,
        19.,  42.,  72.,  81.,  92.,  74., 167.,  36.])

#### According to the answer key customer_type has 4 answers - group, transient (not part of group or contract), Tranisent-Party, Contract. Most bookings have a transient customer type.

In [49]:
Hotels.customer_type.value_counts()

Transient          89713
Transient-Party    25124
Contract            4076
Group                577
Name: customer_type, dtype: int64

#### ADR - Average Daily Rate - divide sum of all lodging by total number of nights. Most often the room was 62 dollars a night.

In [50]:
Hotels.adr.value_counts()

62.00     3754
75.00     2715
90.00     2473
65.00     2418
0.00      1959
          ...
178.53       1
102.71       1
90.44        1
210.80       1
149.68       1
Name: adr, Length: 8879, dtype: int64

#### By far people are not bringing their cars to the hotel. If they do it's one car.

In [51]:
Hotels.required_car_parking_spaces.value_counts()

0.0    112071
1.0      7386
2.0        28
3.0         3
8.0         2
Name: required_car_parking_spaces, dtype: int64

#### Most often the consumers have no special requests. In the off chance there is, it's only 1 or 2.

In [52]:
Hotels.total_of_special_requests.value_counts()

0.0    70369
1.0    33252
2.0    12992
3.0     2497
4.0      340
5.0       40
Name: total_of_special_requests, dtype: int64

#### Nearly doube the amount of people checked-out rather than cancelling.

In [53]:
Hotels.reservation_status.value_counts()

Check-Out    75176
Canceled     43106
No-Show       1208
Name: reservation_status, dtype: int64

#### This question lists the date of the last stauts update for the booking. compare against reservation status. Plot dates in Tableau.

In [54]:
Hotels.reservation_status_date.value_counts()

2015-10-21    1461
2015-07-06     805
2016-11-25     790
2015-01-01     763
2016-01-18     625
              ...
2015-02-26       1
2015-03-10       1
2015-01-18       1
2014-11-18       1
2015-02-12       1
Name: reservation_status_date, Length: 926, dtype: int64

#### This question reveals the company or entity # responsible for booking and or paying for the hotel stay. sample is 500. Plot in Tableau.

In [55]:
Hotels.company.value_counts()

40.0     927
223.0    784
67.0     267
45.0     250
153.0    215
        ...
273.0      1
415.0      1
352.0      1
253.0      1
497.0      1
Name: company, Length: 352, dtype: int64

#### Drop unneeded columns for reasons previously stated 2 columns were removed.

In [56]:
Hotels1 = Hotels.drop(['reservation_id', 'company'], axis=1)
Hotels1

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0.0,342.0,2015.0,July,27.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Resort Hotel,0.0,737.0,2015.0,July,27.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Resort Hotel,0.0,7.0,2015.0,July,27.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Resort Hotel,0.0,13.0,2015.0,July,27.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Resort Hotel,0.0,14.0,2015.0,July,27.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,0.0,0.0,BB,BEL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,394.0,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06
112486,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,9.0,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07
112487,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,9.0,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07
112488,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,89.0,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07
112489,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,0.0,0.0,HB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,9.0,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07

### Reveal and Remove all Null values using dropna()
#### (inplace=True) used since I working in the original variable instead of renaming the variable. Check to make sure all Null Values are gone

In [57]:
Hotels1.isnull().sum()

hotel                               500
is_canceled                         500
lead_time                           500
arrival_date_year                   500
arrival_date_month                  500
arrival_date_week_number            500
arrival_date_day_of_month           500
stays_in_weekend_nights             500
stays_in_week_nights                500
adults                              500
children                            504
babies                              500
meal                                500
country                             988
market_segment                      500
distribution_channel                500
is_repeated_guest                   500
previous_cancellations              500
previous_bookings_not_canceled      500
reserved_room_type                  500
assigned_room_type                  500
booking_changes                     500
deposit_type                        500
agent                             16845
days_in_waiting_list                500
customer_type                       500
adr                                 500
required_car_parking_spaces         500
total_of_special_requests           500
reservation_status                  500
reservation_status_date             500
dtype: int64

In [58]:
Hotels2 = Hotels1.dropna()
Hotels2.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

### Data Recoding - Assess data types and change if appropriate
#### listing all unique answers then converting categorical values to integers for statitical analysis.

In [59]:
Hotels2

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0.0,13.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20
1,Resort Hotel,1.0,32.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,PRT,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,240.0,0.0,Transient,154.00,0.0,0.0,Canceled,2015-06-24
2,Resort Hotel,0.0,315.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,IRL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,171.0,0.0,Transient,96.30,0.0,0.0,Check-Out,2015-07-20
3,Resort Hotel,0.0,8.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20
5,Resort Hotel,0.0,91.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,1.0,0.0,BB,MOZ,Online TA,TA/TO,0.0,0.0,0.0,A,A,4.0,No Deposit,240.0,0.0,Transient,118.50,0.0,3.0,Check-Out,2015-07-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,0.0,0.0,BB,BEL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,394.0,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06
112486,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,9.0,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07
112487,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,9.0,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07
112488,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,89.0,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07
112489,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,0.0,0.0,HB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,9.0,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07

In [60]:
def res_room_type_recode (letter):
    
    if letter == "A":
        return 0
    if letter == "B":
        return 1
    if letter == "C":
        return 2
    if letter == "D":
        return 3
    if letter == "E":
        return 4
    if letter == "F":
        return 5
    if letter == "G":
        return 6
    if letter == "H":
        return 7
    if letter == "L":
        return 8
    if letter == "P":
        return 9
    
Hotels2["res_room_typeR"] = Hotels2["reserved_room_type"].apply(res_room_type_recode)

<ipython-input-60-01ca0bddbced>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Hotels2["res_room_typeR"] = Hotels2["reserved_room_type"].apply(res_room_type_recode)

In [61]:
Hotels2

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,res_room_typeR
0,Resort Hotel,0.0,13.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0
1,Resort Hotel,1.0,32.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,PRT,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,240.0,0.0,Transient,154.00,0.0,0.0,Canceled,2015-06-24,3
2,Resort Hotel,0.0,315.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,IRL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,171.0,0.0,Transient,96.30,0.0,0.0,Check-Out,2015-07-20,0
3,Resort Hotel,0.0,8.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0
5,Resort Hotel,0.0,91.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,1.0,0.0,BB,MOZ,Online TA,TA/TO,0.0,0.0,0.0,A,A,4.0,No Deposit,240.0,0.0,Transient,118.50,0.0,3.0,Check-Out,2015-07-20,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,0.0,0.0,BB,BEL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,394.0,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06,0
112486,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,9.0,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07,4
112487,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,9.0,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07,3
112488,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,89.0,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07,0
112489,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,0.0,0.0,HB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,9.0,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07,0

#### assigned_room_type recode

In [62]:
def assn_room_type_recode (letter):
    
    if letter == "A":
        return 0
    if letter == "B":
        return 1
    if letter == "C":
        return 2
    if letter == "D":
        return 3
    if letter == "E":
        return 4
    if letter == "F":
        return 5
    if letter == "G":
        return 6
    if letter == "H":
        return 7
    if letter == "K":
        return 8
    if letter == "L":
        return 9
    if letter == "P":
        return 10
    
Hotels2["assn_room_typeR"] = Hotels2["assigned_room_type"].apply(assn_room_type_recode)
Hotels2

<ipython-input-62-0986bf088418>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Hotels2["assn_room_typeR"] = Hotels2["assigned_room_type"].apply(assn_room_type_recode)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,res_room_typeR,assn_room_typeR
0,Resort Hotel,0.0,13.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,0.0
1,Resort Hotel,1.0,32.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,PRT,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,240.0,0.0,Transient,154.00,0.0,0.0,Canceled,2015-06-24,3,3.0
2,Resort Hotel,0.0,315.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,IRL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,171.0,0.0,Transient,96.30,0.0,0.0,Check-Out,2015-07-20,0,3.0
3,Resort Hotel,0.0,8.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,3.0
5,Resort Hotel,0.0,91.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,1.0,0.0,BB,MOZ,Online TA,TA/TO,0.0,0.0,0.0,A,A,4.0,No Deposit,240.0,0.0,Transient,118.50,0.0,3.0,Check-Out,2015-07-20,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,0.0,0.0,BB,BEL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,394.0,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06,0,0.0
112486,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,9.0,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07,4,4.0
112487,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,9.0,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07,3,3.0
112488,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,89.0,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07,0,0.0
112489,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,0.0,0.0,HB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,9.0,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07,0,0.0

#### customer_type recode

In [63]:
def cust_type_recode (series):
    
    if series == "Contract":
        return 0
    if series == "Group":
        return 1
    if series == "Transient":
        return 2
    if series == "Transient-Party":
        return 3

Hotels2["cust_typeR"] = Hotels2["customer_type"].apply(cust_type_recode)
Hotels2

<ipython-input-63-155b58651179>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Hotels2["cust_typeR"] = Hotels2["customer_type"].apply(cust_type_recode)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,res_room_typeR,assn_room_typeR,cust_typeR
0,Resort Hotel,0.0,13.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,0.0,2
1,Resort Hotel,1.0,32.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,PRT,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,240.0,0.0,Transient,154.00,0.0,0.0,Canceled,2015-06-24,3,3.0,2
2,Resort Hotel,0.0,315.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,IRL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,171.0,0.0,Transient,96.30,0.0,0.0,Check-Out,2015-07-20,0,3.0,2
3,Resort Hotel,0.0,8.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,3.0,2
5,Resort Hotel,0.0,91.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,1.0,0.0,BB,MOZ,Online TA,TA/TO,0.0,0.0,0.0,A,A,4.0,No Deposit,240.0,0.0,Transient,118.50,0.0,3.0,Check-Out,2015-07-20,0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,0.0,0.0,BB,BEL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,394.0,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06,0,0.0,2
112486,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,9.0,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07,4,4.0,2
112487,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,9.0,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07,3,3.0,2
112488,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,89.0,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07,0,0.0,2
112489,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,0.0,0.0,HB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,9.0,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07,0,0.0,2

#### reservation_status recode

In [64]:
def res_status_recode (series):
    
    if series == "Check-Out":
        return 0
    if series == "Canceled":
        return 1
    if series == "No-Show":
        return 2
    
Hotels2["res_statusR"] = Hotels2["reservation_status"].apply(res_status_recode)
Hotels2

<ipython-input-64-4be36073eced>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Hotels2["res_statusR"] = Hotels2["reservation_status"].apply(res_status_recode)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,res_room_typeR,assn_room_typeR,cust_typeR,res_statusR
0,Resort Hotel,0.0,13.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,0.0,2,0
1,Resort Hotel,1.0,32.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,PRT,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,240.0,0.0,Transient,154.00,0.0,0.0,Canceled,2015-06-24,3,3.0,2,1
2,Resort Hotel,0.0,315.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,IRL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,171.0,0.0,Transient,96.30,0.0,0.0,Check-Out,2015-07-20,0,3.0,2,0
3,Resort Hotel,0.0,8.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,3.0,2,0
5,Resort Hotel,0.0,91.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,1.0,0.0,BB,MOZ,Online TA,TA/TO,0.0,0.0,0.0,A,A,4.0,No Deposit,240.0,0.0,Transient,118.50,0.0,3.0,Check-Out,2015-07-20,0,0.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,0.0,0.0,BB,BEL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,394.0,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06,0,0.0,2,0
112486,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,9.0,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07,4,4.0,2,0
112487,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,9.0,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07,3,3.0,2,0
112488,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,89.0,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07,0,0.0,2,0
112489,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,0.0,0.0,HB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,9.0,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07,0,0.0,2,0

### hotel

In [65]:
def hotel_recode (series):
    
    if series == "City Hotel":
        return 0
    if series == "city HOTEL":
        return 0
    if series == "CITY hotel":
        return 0
    if series == "Resort Hotel":
        return 1
    if series == "RESORT hotel":
        return 1
    if series == "Resort HOTEL":
        return 1
    
Hotels2["hotelR"] = Hotels2["hotel"].apply(hotel_recode)
Hotels2

<ipython-input-65-5cea9fedf824>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Hotels2["hotelR"] = Hotels2["hotel"].apply(hotel_recode)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,res_room_typeR,assn_room_typeR,cust_typeR,res_statusR,hotelR
0,Resort Hotel,0.0,13.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,0.0,2,0,1
1,Resort Hotel,1.0,32.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,PRT,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,240.0,0.0,Transient,154.00,0.0,0.0,Canceled,2015-06-24,3,3.0,2,1,1
2,Resort Hotel,0.0,315.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,IRL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,171.0,0.0,Transient,96.30,0.0,0.0,Check-Out,2015-07-20,0,3.0,2,0,1
3,Resort Hotel,0.0,8.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,3.0,2,0,1
5,Resort Hotel,0.0,91.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,1.0,0.0,BB,MOZ,Online TA,TA/TO,0.0,0.0,0.0,A,A,4.0,No Deposit,240.0,0.0,Transient,118.50,0.0,3.0,Check-Out,2015-07-20,0,0.0,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,0.0,0.0,BB,BEL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,394.0,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06,0,0.0,2,0,0
112486,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,9.0,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07,4,4.0,2,0,0
112487,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,9.0,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07,3,3.0,2,0,0
112488,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,89.0,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07,0,0.0,2,0,0
112489,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,0.0,0.0,HB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,9.0,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07,0,0.0,2,0,0

### arrival_date_month

In [66]:
def arrival_date_month_recode (series):
    
    if series == "January":
        return 0
    if series == "JANUARY":
        return 0
    if series == "February":
        return 1
    if series == "FEBRUARY":
        return 1
    if series == "March":
        return 2
    if series == "MARCH":
        return 2
    if series == "April":
        return 3
    if series == "APRIL":
        return 3
    if series == "May":
        return 4
    if series == "MAY":
        return 4
    if series == "June":
        return 5
    if series == "JUNE":
        return 5
    if series == "July":
        return 6
    if series == "July":
        return 6
    if series == "August":
        return 7
    if series == "AUGUST":
        return 7
    if series == "September":
        return 8
    if series == "SEPTEMBER":
        return 8
    if series == "October":
        return 9
    if series == "OCTOBER":
        return 9
    if series == "November":
        return 10
    if series == "NOVEMBER":
        return 10
    if series == "December":
        return 11
    if series == "DECEMBER":
        return 11
    
Hotels2["arrival_date_monthR"] = Hotels2["arrival_date_month"].apply(arrival_date_month_recode)
Hotels2

<ipython-input-66-1a6b11c60d65>:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Hotels2["arrival_date_monthR"] = Hotels2["arrival_date_month"].apply(arrival_date_month_recode)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,res_room_typeR,assn_room_typeR,cust_typeR,res_statusR,hotelR,arrival_date_monthR
0,Resort Hotel,0.0,13.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,0.0,2,0,1,6.0
1,Resort Hotel,1.0,32.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,PRT,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,240.0,0.0,Transient,154.00,0.0,0.0,Canceled,2015-06-24,3,3.0,2,1,1,6.0
2,Resort Hotel,0.0,315.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,IRL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,171.0,0.0,Transient,96.30,0.0,0.0,Check-Out,2015-07-20,0,3.0,2,0,1,6.0
3,Resort Hotel,0.0,8.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,3.0,2,0,1,6.0
5,Resort Hotel,0.0,91.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,1.0,0.0,BB,MOZ,Online TA,TA/TO,0.0,0.0,0.0,A,A,4.0,No Deposit,240.0,0.0,Transient,118.50,0.0,3.0,Check-Out,2015-07-20,0,0.0,2,0,1,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,0.0,0.0,BB,BEL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,394.0,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06,0,0.0,2,0,0,7.0
112486,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,9.0,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07,4,4.0,2,0,0,7.0
112487,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,9.0,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07,3,3.0,2,0,0,7.0
112488,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,89.0,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07,0,0.0,2,0,0,7.0
112489,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,0.0,0.0,HB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,9.0,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07,0,0.0,2,0,0,7.0

### Meal

In [67]:
def meal_recode (series):
    
    if series == "BB":
        return 0
    if series == "HB":
        return 1
    if series == "SC":
        return 2
    if series == "FB":
        return 3
    if series == "Undefined":
        return 4
    
Hotels2["mealR"] = Hotels2["meal"].apply(meal_recode)
Hotels2

<ipython-input-67-b707248b77c5>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Hotels2["mealR"] = Hotels2["meal"].apply(meal_recode)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,res_room_typeR,assn_room_typeR,cust_typeR,res_statusR,hotelR,arrival_date_monthR,mealR
0,Resort Hotel,0.0,13.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,0.0,2,0,1,6.0,0
1,Resort Hotel,1.0,32.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,PRT,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,240.0,0.0,Transient,154.00,0.0,0.0,Canceled,2015-06-24,3,3.0,2,1,1,6.0,0
2,Resort Hotel,0.0,315.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,IRL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,171.0,0.0,Transient,96.30,0.0,0.0,Check-Out,2015-07-20,0,3.0,2,0,1,6.0,0
3,Resort Hotel,0.0,8.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,3.0,2,0,1,6.0,0
5,Resort Hotel,0.0,91.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,1.0,0.0,BB,MOZ,Online TA,TA/TO,0.0,0.0,0.0,A,A,4.0,No Deposit,240.0,0.0,Transient,118.50,0.0,3.0,Check-Out,2015-07-20,0,0.0,2,0,1,6.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,0.0,0.0,BB,BEL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,394.0,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06,0,0.0,2,0,0,7.0,0
112486,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,9.0,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07,4,4.0,2,0,0,7.0,0
112487,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,9.0,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07,3,3.0,2,0,0,7.0,0
112488,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,89.0,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07,0,0.0,2,0,0,7.0,0
112489,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,0.0,0.0,HB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,9.0,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07,0,0.0,2,0,0,7.0,1

### deposit_type

In [68]:
def deposit_type_recode (series):
    
    if series == "No Deposit":
        return 0
    if series == "Non Refund":
        return 1
    if series == "Refundable":
        return 2
    
Hotels2["deposit_typeR"] = Hotels2["deposit_type"].apply(deposit_type_recode)
Hotels2

<ipython-input-68-b52d9af09451>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Hotels2["deposit_typeR"] = Hotels2["deposit_type"].apply(deposit_type_recode)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,res_room_typeR,assn_room_typeR,cust_typeR,res_statusR,hotelR,arrival_date_monthR,mealR,deposit_typeR
0,Resort Hotel,0.0,13.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,0.0,2,0,1,6.0,0,0
1,Resort Hotel,1.0,32.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,PRT,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,240.0,0.0,Transient,154.00,0.0,0.0,Canceled,2015-06-24,3,3.0,2,1,1,6.0,0,0
2,Resort Hotel,0.0,315.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,IRL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,171.0,0.0,Transient,96.30,0.0,0.0,Check-Out,2015-07-20,0,3.0,2,0,1,6.0,0,0
3,Resort Hotel,0.0,8.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,3.0,2,0,1,6.0,0,0
5,Resort Hotel,0.0,91.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,1.0,0.0,BB,MOZ,Online TA,TA/TO,0.0,0.0,0.0,A,A,4.0,No Deposit,240.0,0.0,Transient,118.50,0.0,3.0,Check-Out,2015-07-20,0,0.0,2,0,1,6.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,0.0,0.0,BB,BEL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,394.0,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06,0,0.0,2,0,0,7.0,0,0
112486,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,9.0,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07,4,4.0,2,0,0,7.0,0,0
112487,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,9.0,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07,3,3.0,2,0,0,7.0,0,0
112488,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,89.0,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07,0,0.0,2,0,0,7.0,0,0
112489,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,0.0,0.0,HB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,9.0,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07,0,0.0,2,0,0,7.0,1,0

### market_segment

In [69]:
def market_segment_recode (series):
    
    if series == "Online TA":
        return 0
    if series == "Offline TA/TO":
        return 1
    if series == "Groups":
        return 2
    if series == "Direct":
        return 3
    if series == "Corporate":
        return 4
    if series == "Complementary":
        return 5
    if series == "Aviation":
        return 6
    if series == "Undefined":
        return 7
    
Hotels2["market_segmentR"] = Hotels2["market_segment"].apply(market_segment_recode)
Hotels2

<ipython-input-69-466723884c1f>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Hotels2["market_segmentR"] = Hotels2["market_segment"].apply(market_segment_recode)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,res_room_typeR,assn_room_typeR,cust_typeR,res_statusR,hotelR,arrival_date_monthR,mealR,deposit_typeR,market_segmentR
0,Resort Hotel,0.0,13.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,0.0,2,0,1,6.0,0,0,0
1,Resort Hotel,1.0,32.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,PRT,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,240.0,0.0,Transient,154.00,0.0,0.0,Canceled,2015-06-24,3,3.0,2,1,1,6.0,0,0,0
2,Resort Hotel,0.0,315.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,IRL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,171.0,0.0,Transient,96.30,0.0,0.0,Check-Out,2015-07-20,0,3.0,2,0,1,6.0,0,0,1
3,Resort Hotel,0.0,8.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,3.0,2,0,1,6.0,0,0,0
5,Resort Hotel,0.0,91.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,1.0,0.0,BB,MOZ,Online TA,TA/TO,0.0,0.0,0.0,A,A,4.0,No Deposit,240.0,0.0,Transient,118.50,0.0,3.0,Check-Out,2015-07-20,0,0.0,2,0,1,6.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,0.0,0.0,BB,BEL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,394.0,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06,0,0.0,2,0,0,7.0,0,0,1
112486,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,9.0,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07,4,4.0,2,0,0,7.0,0,0,0
112487,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,9.0,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07,3,3.0,2,0,0,7.0,0,0,0
112488,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,89.0,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07,0,0.0,2,0,0,7.0,0,0,0
112489,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,0.0,0.0,HB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,9.0,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07,0,0.0,2,0,0,7.0,1,0,0

### distribution_channel

In [70]:
def dist_channel_recode (series):
    
    if series == "TA/TO":
        return 0
    if series == "Direct":
        return 1
    if series == "Corporate":
        return 2
    if series == "GDS":
        return 3
    if series == "Undefined":
        return 4

Hotels2["dist_channelR"] = Hotels2["distribution_channel"].apply(dist_channel_recode)
Hotels2

<ipython-input-70-cd99e99fde4d>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Hotels2["dist_channelR"] = Hotels2["distribution_channel"].apply(dist_channel_recode)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,res_room_typeR,assn_room_typeR,cust_typeR,res_statusR,hotelR,arrival_date_monthR,mealR,deposit_typeR,market_segmentR,dist_channelR
0,Resort Hotel,0.0,13.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,0.0,2,0,1,6.0,0,0,0,0
1,Resort Hotel,1.0,32.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,PRT,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,240.0,0.0,Transient,154.00,0.0,0.0,Canceled,2015-06-24,3,3.0,2,1,1,6.0,0,0,0,0
2,Resort Hotel,0.0,315.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,IRL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,171.0,0.0,Transient,96.30,0.0,0.0,Check-Out,2015-07-20,0,3.0,2,0,1,6.0,0,0,1,0
3,Resort Hotel,0.0,8.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,3.0,2,0,1,6.0,0,0,0,0
5,Resort Hotel,0.0,91.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,1.0,0.0,BB,MOZ,Online TA,TA/TO,0.0,0.0,0.0,A,A,4.0,No Deposit,240.0,0.0,Transient,118.50,0.0,3.0,Check-Out,2015-07-20,0,0.0,2,0,1,6.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,0.0,0.0,BB,BEL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,394.0,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06,0,0.0,2,0,0,7.0,0,0,1,0
112486,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,9.0,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07,4,4.0,2,0,0,7.0,0,0,0,0
112487,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,9.0,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07,3,3.0,2,0,0,7.0,0,0,0,0
112488,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,89.0,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07,0,0.0,2,0,0,7.0,0,0,0,0
112489,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,0.0,0.0,HB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,9.0,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07,0,0.0,2,0,0,7.0,1,0,0,0

#### Recode into 3 categories GBR, PRT and then everything else.

In [71]:
def country_recode (series):
    
    if series == "GBR":
        return 0
    if series == "PRT":
        return 1
    else:
        return 2
    
Hotels2["countryR"] = Hotels2["country"].apply(country_recode)
Hotels2

<ipython-input-71-a9a9ad9e123f>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Hotels2["countryR"] = Hotels2["country"].apply(country_recode)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,res_room_typeR,assn_room_typeR,cust_typeR,res_statusR,hotelR,arrival_date_monthR,mealR,deposit_typeR,market_segmentR,dist_channelR,countryR
0,Resort Hotel,0.0,13.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,0.0,2,0,1,6.0,0,0,0,0,2
1,Resort Hotel,1.0,32.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,PRT,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,240.0,0.0,Transient,154.00,0.0,0.0,Canceled,2015-06-24,3,3.0,2,1,1,6.0,0,0,0,0,1
2,Resort Hotel,0.0,315.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,IRL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,171.0,0.0,Transient,96.30,0.0,0.0,Check-Out,2015-07-20,0,3.0,2,0,1,6.0,0,0,1,0,2
3,Resort Hotel,0.0,8.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,3.0,2,0,1,6.0,0,0,0,0,0
5,Resort Hotel,0.0,91.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,1.0,0.0,BB,MOZ,Online TA,TA/TO,0.0,0.0,0.0,A,A,4.0,No Deposit,240.0,0.0,Transient,118.50,0.0,3.0,Check-Out,2015-07-20,0,0.0,2,0,1,6.0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,0.0,0.0,BB,BEL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,394.0,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06,0,0.0,2,0,0,7.0,0,0,1,0,2
112486,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,9.0,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07,4,4.0,2,0,0,7.0,0,0,0,0,2
112487,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,9.0,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07,3,3.0,2,0,0,7.0,0,0,0,0,2
112488,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,89.0,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07,0,0.0,2,0,0,7.0,0,0,0,0,0
112489,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,0.0,0.0,HB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,9.0,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07,0,0.0,2,0,0,7.0,1,0,0,0,2

### re-check on the null values - if any remove.

In [72]:
Hotels2.isnull().sum()

hotel                               0
is_canceled                         0
lead_time                           0
arrival_date_year                   0
arrival_date_month                  0
arrival_date_week_number            0
arrival_date_day_of_month           0
stays_in_weekend_nights             0
stays_in_week_nights                0
adults                              0
children                            0
babies                              0
meal                                0
country                             0
market_segment                      0
distribution_channel                0
is_repeated_guest                   0
previous_cancellations              0
previous_bookings_not_canceled      0
reserved_room_type                  0
assigned_room_type                  0
booking_changes                     0
deposit_type                        0
agent                               0
days_in_waiting_list                0
customer_type                       0
adr                                 0
required_car_parking_spaces         0
total_of_special_requests           0
reservation_status                  0
reservation_status_date             0
res_room_typeR                      0
assn_room_typeR                   273
cust_typeR                          0
res_statusR                         0
hotelR                              0
arrival_date_monthR                 4
mealR                               0
deposit_typeR                       0
market_segmentR                     0
dist_channelR                       0
countryR                            0
dtype: int64

### could not chart in Tableau due to dropping the original columns I recoded. Took me a long time to figure that out and I am back tracking to make sure I keep all those columns. No need to drop them.

In [73]:
Hotels30 = Hotels2.dropna()
Hotels30.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
res_room_typeR                    0
assn_room_typeR                   0
cust_typeR                        0
res_statusR                       0
hotelR                            0
arrival_date_monthR               0
mealR                             0
deposit_typeR                     0
market_segmentR                   0
dist_channelR                     0
countryR                          0
dtype: int64

## Descriptive statistics
#### display .info() to find out the type of data for each question

In [74]:
Hotels30.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102257 entries, 0 to 112489
Data columns (total 42 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           102257 non-null  object
 1   is_canceled                     102257 non-null  float64
 2   lead_time                       102257 non-null  float64
 3   arrival_date_year               102257 non-null  float64
 4   arrival_date_month              102257 non-null  object
 5   arrival_date_week_number        102257 non-null  float64
 6   arrival_date_day_of_month       102257 non-null  float64
 7   stays_in_weekend_nights         102257 non-null  float64
 8   stays_in_week_nights            102257 non-null  float64
 9   adults                          102257 non-null  float64
 10  children                        102257 non-null  float64
 11  babies                          102257 non-null  float64
 12  meal                            102257 non-null  object
 13  country                         102257 non-null  object
 14  market_segment                  102257 non-null  object
 15  distribution_channel            102257 non-null  object
 16  is_repeated_guest               102257 non-null  float64
 17  previous_cancellations          102257 non-null  float64
 18  previous_bookings_not_canceled  102257 non-null  float64
 19  reserved_room_type              102257 non-null  object
 20  assigned_room_type              102257 non-null  object
 21  booking_changes                 102257 non-null  float64
 22  deposit_type                    102257 non-null  object
 23  agent                           102257 non-null  float64
 24  days_in_waiting_list            102257 non-null  float64
 25  customer_type                   102257 non-null  object
 26  adr                             102257 non-null  float64
 27  required_car_parking_spaces     102257 non-null  float64
 28  total_of_special_requests       102257 non-null  float64
 29  reservation_status              102257 non-null  object
 30  reservation_status_date         102257 non-null  object
 31  res_room_typeR                  102257 non-null  int64
 32  assn_room_typeR                 102257 non-null  float64
 33  cust_typeR                      102257 non-null  int64
 34  res_statusR                     102257 non-null  int64
 35  hotelR                          102257 non-null  int64
 36  arrival_date_monthR             102257 non-null  float64
 37  mealR                           102257 non-null  int64
 38  deposit_typeR                   102257 non-null  int64
 39  market_segmentR                 102257 non-null  int64
 40  dist_channelR                   102257 non-null  int64
 41  countryR                        102257 non-null  int64
dtypes: float64(21), int64(9), object(12)
memory usage: 33.5+ MB

### THIS WAS THE WRONG MOVE -create a new df with the original columns dropped that were recoded. Display all columns.

In [75]:
Hotels4 = Hotels30.drop(['hotel', 'arrival_date_month', 'country', 'meal', 'market_segment', 'distribution_channel', 'reserved_room_type', 'assigned_room_type', 'deposit_type', 'customer_type', 'reservation_status', 'reservation_status_date'], axis=1)
Hotels4

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,res_room_typeR,assn_room_typeR,cust_typeR,res_statusR,hotelR,arrival_date_monthR,mealR,deposit_typeR,market_segmentR,dist_channelR,countryR
0,0.0,13.0,2015.0,29.0,17.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,240.0,0.0,126.30,0.0,2.0,0,0.0,2,0,1,6.0,0,0,0,0,2
1,1.0,32.0,2015.0,29.0,17.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,240.0,0.0,154.00,0.0,0.0,3,3.0,2,1,1,6.0,0,0,0,0,1
2,0.0,315.0,2015.0,29.0,17.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,171.0,0.0,96.30,0.0,0.0,0,3.0,2,0,1,6.0,0,0,1,0,2
3,0.0,8.0,2015.0,29.0,17.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,240.0,0.0,126.30,0.0,2.0,0,3.0,2,0,1,6.0,0,0,0,0,0
5,0.0,91.0,2015.0,29.0,17.0,1.0,2.0,2.0,1.0,0.0,0.0,0.0,0.0,4.0,240.0,0.0,118.50,0.0,3.0,0,0.0,2,0,1,6.0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,0.0,23.0,2017.0,35.0,30.0,2.0,5.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,394.0,0.0,96.14,0.0,0.0,0,0.0,2,0,0,7.0,0,0,1,0,2
112486,0.0,102.0,2017.0,35.0,31.0,2.0,5.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,225.43,0.0,2.0,4,4.0,2,0,0,7.0,0,0,0,0,2
112487,0.0,34.0,2017.0,35.0,31.0,2.0,5.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,157.71,0.0,4.0,3,3.0,2,0,0,7.0,0,0,0,0,2
112488,0.0,109.0,2017.0,35.0,31.0,2.0,5.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,89.0,0.0,104.40,0.0,0.0,0,0.0,2,0,0,7.0,0,0,0,0,0
112489,0.0,205.0,2017.0,35.0,29.0,2.0,7.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,151.20,0.0,2.0,0,0.0,2,0,0,7.0,1,0,0,0,2

###

In [76]:
Hotels30

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,res_room_typeR,assn_room_typeR,cust_typeR,res_statusR,hotelR,arrival_date_monthR,mealR,deposit_typeR,market_segmentR,dist_channelR,countryR
0,Resort Hotel,0.0,13.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,0.0,2,0,1,6.0,0,0,0,0,2
1,Resort Hotel,1.0,32.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,PRT,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,240.0,0.0,Transient,154.00,0.0,0.0,Canceled,2015-06-24,3,3.0,2,1,1,6.0,0,0,0,0,1
2,Resort Hotel,0.0,315.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,IRL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,171.0,0.0,Transient,96.30,0.0,0.0,Check-Out,2015-07-20,0,3.0,2,0,1,6.0,0,0,1,0,2
3,Resort Hotel,0.0,8.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,D,0.0,No Deposit,240.0,0.0,Transient,126.30,0.0,2.0,Check-Out,2015-07-20,0,3.0,2,0,1,6.0,0,0,0,0,0
5,Resort Hotel,0.0,91.0,2015.0,July,29.0,17.0,1.0,2.0,2.0,1.0,0.0,BB,MOZ,Online TA,TA/TO,0.0,0.0,0.0,A,A,4.0,No Deposit,240.0,0.0,Transient,118.50,0.0,3.0,Check-Out,2015-07-20,0,0.0,2,0,1,6.0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112485,City Hotel,0.0,23.0,2017.0,August,35.0,30.0,2.0,5.0,2.0,0.0,0.0,BB,BEL,Offline TA/TO,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,394.0,0.0,Transient,96.14,0.0,0.0,Check-Out,2017-09-06,0,0.0,2,0,0,7.0,0,0,1,0,2
112486,City Hotel,0.0,102.0,2017.0,August,35.0,31.0,2.0,5.0,3.0,0.0,0.0,BB,FRA,Online TA,TA/TO,0.0,0.0,0.0,E,E,0.0,No Deposit,9.0,0.0,Transient,225.43,0.0,2.0,Check-Out,2017-09-07,4,4.0,2,0,0,7.0,0,0,0,0,2
112487,City Hotel,0.0,34.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,DEU,Online TA,TA/TO,0.0,0.0,0.0,D,D,0.0,No Deposit,9.0,0.0,Transient,157.71,0.0,4.0,Check-Out,2017-09-07,3,3.0,2,0,0,7.0,0,0,0,0,2
112488,City Hotel,0.0,109.0,2017.0,August,35.0,31.0,2.0,5.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,89.0,0.0,Transient,104.40,0.0,0.0,Check-Out,2017-09-07,0,0.0,2,0,0,7.0,0,0,0,0,0
112489,City Hotel,0.0,205.0,2017.0,August,35.0,29.0,2.0,7.0,2.0,0.0,0.0,HB,DEU,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,No Deposit,9.0,0.0,Transient,151.20,0.0,2.0,Check-Out,2017-09-07,0,0.0,2,0,0,7.0,1,0,0,0,2

### Print descriptive statistics for the entire data frame

In [77]:
Hotels30.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,res_room_typeR,assn_room_typeR,cust_typeR,res_statusR,hotelR,arrival_date_monthR,mealR,deposit_typeR,market_segmentR,dist_channelR,countryR
count,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000,102257.000000
mean,0.392579,112.117840,2016.161994,27.339116,15.812893,0.977058,2.587539,1.899665,0.110809,0.007628,0.013701,0.077696,0.024341,0.200417,85.769307,2.634744,104.843051,0.052319,0.604682,1.008254,1.275942,2.117527,0.402320,0.303930,5.593309,0.382614,0.123395,0.760672,0.095143,1.424479
std,0.488327,107.841678,0.703415,13.303727,8.792617,1.000900,1.896472,0.491484,0.410217,0.096693,0.116246,0.760519,0.436538,0.617657,110.419827,18.851428,49.927312,0.223897,0.799082,1.699106,1.817699,0.590118,0.509845,0.459955,3.024430,0.756687,0.330316,0.988729,0.345260,0.674990
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,-6.380000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,26.000000,2016.000000,17.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.000000,73.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,0.000000,80.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,0.000000,96.300000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,2.000000
75%,1.000000,169.000000,2017.000000,38.000000,24.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,0.000000,128.000000,0.000000,1.000000,3.000000,3.000000,2.000000,1.000000,1.000000,8.000000,0.000000,0.000000,1.000000,0.000000,2.000000
max,1.000000,629.000000,2017.000000,53.000000,31.000000,16.000000,41.000000,26.000000,3.000000,10.000000,1.000000,26.000000,50.000000,18.000000,535.000000,391.000000,5400.000000,3.000000,5.000000,7.000000,8.000000,3.000000,2.000000,1.000000,11.000000,4.000000,2.000000,6.000000,3.000000,2.000000

#### Heat Map shows reservation status and is cancelled at .98 correlation, arrival date week and arrival date month .99, reserved room type and assigned room type highly corrolated at .86, agent and hotelR correlate at .79. Honorable mentions for market segmentR and distribution channelR .57, deposit typeR and is cancelledR .46

In [78]:
Hotels30.corr(method='pearson').style.format("{:.2}").background_gradient(cmap=plt.get_cmap('coolwarm'), axis=1)

### data for those who checked in with children, babies

In [79]:
hotels123 = pd.read_csv ('/Users/chercher/Desktop/hotels data/clean data/with kids/Hotels4clean1a.csv')
hotels123

,Unnamed: 0,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,res_room_typeR,assn_room_typeR,cust_typeR,res_statusR,hotelR,arrival_date_monthR,mealR,deposit_typeR,market_segmentR,dist_channelR,countryR
0,0,0,13,2015,29,17,1,2,2,0,0,0,0,0,0,240,0,126,0,2,0,0,2,0,1,6,0,0,0,0,2
1,1,1,32,2015,29,17,1,2,2,0,0,0,0,0,0,240,0,154,0,0,3,3,2,1,1,6,0,0,0,0,1
2,2,0,315,2015,29,17,1,2,2,0,0,0,0,0,0,171,0,96,0,0,0,3,2,0,1,6,0,0,1,0,2
3,3,0,8,2015,29,17,1,2,2,0,0,0,0,0,0,240,0,126,0,2,0,3,2,0,1,6,0,0,0,0,0
4,5,0,91,2015,29,17,1,2,2,1,0,0,0,0,4,240,0,119,0,3,0,0,2,0,1,6,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102252,112485,0,23,2017,35,30,2,5,2,0,0,0,0,0,0,394,0,96,0,0,0,0,2,0,0,7,0,0,1,0,2
102253,112486,0,102,2017,35,31,2,5,3,0,0,0,0,0,0,9,0,225,0,2,4,4,2,0,0,7,0,0,0,0,2
102254,112487,0,34,2017,35,31,2,5,2,0,0,0,0,0,0,9,0,158,0,4,3,3,2,0,0,7,0,0,0,0,2
102255,112488,0,109,2017,35,31,2,5,2,0,0,0,0,0,0,89,0,104,0,0,0,0,2,0,0,7,0,0,0,0,0
102256,112489,0,205,2017,35,29,2,7,2,0,0,0,0,0,0,9,0,151,0,2,0,0,2,0,0,7,1,0,0,0,2

In [80]:
for col in hotels123.columns:
    print(col)

Unnamed: 0
is_canceled
lead_time
arrival_date_year
arrival_date_week_number
arrival_date_day_of_month
stays_in_weekend_nights
stays_in_week_nights
adults
children
babies
is_repeated_guest
previous_cancellations
previous_bookings_not_canceled
booking_changes
agent
days_in_waiting_list
adr
required_car_parking_spaces
total_of_special_requests
res_room_typeR
assn_room_typeR
cust_typeR
res_statusR
hotelR
arrival_date_monthR
mealR
deposit_typeR
market_segmentR
dist_channelR
countryR

### subset data to show only adults who checked in with children. (babies is a subset of children not factoring in babies).

In [81]:
Hotels456 = hotels123[hotels123["children"].isin([1, 2, 3, 10])]
Hotels456

,Unnamed: 0,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,res_room_typeR,assn_room_typeR,cust_typeR,res_statusR,hotelR,arrival_date_monthR,mealR,deposit_typeR,market_segmentR,dist_channelR,countryR
4,5,0,91,2015,29,17,1,2,2,1,0,0,0,0,4,240,0,119,0,3,0,0,2,0,1,6,0,0,0,0,2
8,10,0,108,2015,29,18,2,4,2,1,0,0,0,0,1,240,0,147,1,2,0,0,2,0,1,6,1,0,0,0,2
9,11,1,37,2015,29,18,2,4,2,2,0,0,0,0,0,242,0,168,0,0,2,2,2,1,1,6,1,0,0,0,1
14,17,1,123,2015,29,18,2,2,2,1,1,0,0,0,1,240,0,157,0,2,4,4,2,1,1,6,0,0,0,0,1
15,18,1,42,2015,29,18,2,3,2,2,0,0,0,0,0,240,0,210,0,0,7,7,2,1,1,6,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102137,112370,0,0,2017,35,29,0,3,2,1,0,0,0,0,1,9,0,135,0,2,0,3,2,0,0,7,0,0,0,0,2
102154,112387,0,167,2017,35,27,2,4,2,1,0,0,0,0,1,9,0,178,0,0,3,3,2,0,0,7,0,0,0,0,2
102160,112393,0,243,2017,35,30,0,3,2,2,0,0,0,0,0,9,0,189,0,3,5,5,2,0,0,7,0,0,0,0,2
102185,112418,0,160,2017,35,29,0,5,2,1,0,0,0,0,0,9,0,154,0,0,0,0,2,0,0,7,0,0,0,0,0
102186,112419,0,45,2017,35,28,1,5,2,2,0,0,0,0,1,7,0,194,0,1,5,5,2,0,0,7,0,0,0,0,0

### there are 7,958 children checked in

In [82]:
Hotels456.children.value_counts

<bound method IndexOpsMixin.value_counts of 4         1
8         1
9         2
14        1
15        2
         ..
102137    1
102154    1
102160    2
102185    1
102186    2
Name: children, Length: 7958, dtype: int64>

In [83]:
Hotels456.children.unique()

array([1, 2, 3])

### subset data to show adults who checked in WITHOUT children totaling 94,299.

In [84]:
Hotels789 = hotels123[hotels123["children"].isin([0])]
Hotels789

,Unnamed: 0,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,res_room_typeR,assn_room_typeR,cust_typeR,res_statusR,hotelR,arrival_date_monthR,mealR,deposit_typeR,market_segmentR,dist_channelR,countryR
0,0,0,13,2015,29,17,1,2,2,0,0,0,0,0,0,240,0,126,0,2,0,0,2,0,1,6,0,0,0,0,2
1,1,1,32,2015,29,17,1,2,2,0,0,0,0,0,0,240,0,154,0,0,3,3,2,1,1,6,0,0,0,0,1
2,2,0,315,2015,29,17,1,2,2,0,0,0,0,0,0,171,0,96,0,0,0,3,2,0,1,6,0,0,1,0,2
3,3,0,8,2015,29,17,1,2,2,0,0,0,0,0,0,240,0,126,0,2,0,3,2,0,1,6,0,0,0,0,0
5,6,0,3,2015,29,17,1,2,2,0,0,0,0,0,0,240,0,116,1,1,0,2,2,0,1,6,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102252,112485,0,23,2017,35,30,2,5,2,0,0,0,0,0,0,394,0,96,0,0,0,0,2,0,0,7,0,0,1,0,2
102253,112486,0,102,2017,35,31,2,5,3,0,0,0,0,0,0,9,0,225,0,2,4,4,2,0,0,7,0,0,0,0,2
102254,112487,0,34,2017,35,31,2,5,2,0,0,0,0,0,0,9,0,158,0,4,3,3,2,0,0,7,0,0,0,0,2
102255,112488,0,109,2017,35,31,2,5,2,0,0,0,0,0,0,89,0,104,0,0,0,0,2,0,0,7,0,0,0,0,0
102256,112489,0,205,2017,35,29,2,7,2,0,0,0,0,0,0,9,0,151,0,2,0,0,2,0,0,7,1,0,0,0,2

In [85]:
Hotels789a = Hotels789.adults.value_counts
Hotels789a

<bound method IndexOpsMixin.value_counts of 0         2
1         2
2         2
3         2
5         2
         ..
102252    2
102253    3
102254    2
102255    2
102256    2
Name: adults, Length: 94299, dtype: int64>

In [86]:
Hotels789.children.unique()

array([0])

### Export Hotels data to .csv use in Tableau for visualizations - THIS WAS DIFFICULT - I did not keep the original columns I recoded so I could not make meaningful visualizations.correcting that now

In [87]:
Hotels4.to_csv('Hotels4clean.csv')

In [88]:
Hotels789.to_csv('Hotels4clean1b.csv')

In [89]:
Hotels.to_csv('mergedUncleanDATA.csv')

In [90]:
Hotels30.to_csv('usethis.csv')

### Show the highest number in each column
#### looking to see what the highest average daily rate was

In [91]:
Hotels30.max(axis = 0, numeric_only=True)

is_canceled                          1.0
lead_time                          629.0
arrival_date_year                 2017.0
arrival_date_week_number            53.0
arrival_date_day_of_month           31.0
stays_in_weekend_nights             16.0
stays_in_week_nights                41.0
adults                              26.0
children                             3.0
babies                              10.0
is_repeated_guest                    1.0
previous_cancellations              26.0
previous_bookings_not_canceled      50.0
booking_changes                     18.0
agent                              535.0
days_in_waiting_list               391.0
adr                               5400.0
required_car_parking_spaces          3.0
total_of_special_requests            5.0
res_room_typeR                       7.0
assn_room_typeR                      8.0
cust_typeR                           3.0
res_statusR                          2.0
hotelR                               1.0
arrival_date_monthR                 11.0
mealR                                4.0
deposit_typeR                        2.0
market_segmentR                      6.0
dist_channelR                        3.0
countryR                             2.0
dtype: float64

### Average of the average daily room rate

In [92]:
df = Hotels30['adr'].mean()
print(df)

104.84305113585877

### Average number of nights for all stays

In [93]:
Allstays = Hotels30['stays_in_weekend_nights']+ Hotels30['stays_in_week_nights']
print('The average range of all stays is: {}'.format(round(Allstays.mean(),2)))

The average range of all stays is: 3.56

### Which countries have the most traverlers? 
#### recoded into GBR(The United Kingdom)= 10,804, PRT(Portugal)= 37,243 and all other countries = 54,210

In [94]:
df2 = Hotels30.groupby(['countryR'])['countryR'].count()
df2

countryR
0    10804
1    37243
2    54210
Name: countryR, dtype: int64

### how many reservations were canceled and how many were not?
### not canceled = 62,113, canceled = 40,144

In [95]:
df3=Hotels30['is_canceled'].value_counts()
df3

0.0    62113
1.0    40144
Name: is_canceled, dtype: int64

### make a pie chart for is_canceled

In [96]:
labels = 'Canceled', 'Not Canceled'
sizes = [40144, 62113]

fig, ax1 = plt.subplots()
ax1.pie(sizes, labels = labels)
ax.1axis('equal')
plt.show()

SyntaxError: invalid syntax (<ipython-input-96-642a72b738be>, line 6)

### average number of special requests

In [97]:
df4 = Hotels30['total_of_special_requests'].mean()
df4

0.6046823200367701